name: Run BeyondSilence

on:
  workflow_dispatch: # Manually trigger
  schedule:
    - cron: "0 12 * * *" # Every day at 12:00 (UTC) or 4:00 (UTC+8)

permissions: write-all

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Installing requirements
        run: |
          pip install -r requirements.txt
      - name: Run BeyondSilence
        env:
          BEYONDSILENCE_CONFIG: ${{ secrets.BEYONDSILENCE_CONFIG }}
          BEYONDSILENCE_KEYS: ${{ secrets.BEYONDSILENCE_KEYS }}
        run: |
          python -m BeyondSilence
      - uses: actions/upload-artifact@v3
        continue-on-error: true # Don't fail the workflow
        with:
          name: output.txt
          path: output.txt
      - name: Commit files
        continue-on-error: true # Don't fail the workflow
        run: |
          git add .
          git config --global user.email "bot@github.com"
          git config --global user.name "Github Bot"
          git commit -m "Update by Github Action"
      - name: Push changes
        continue-on-error: true # Don't fail the workflow
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
